spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TskManagerDb?allowPublicKeyRetrieval=true&useSSL=false
    username: david
    password: david123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

#logging:
#  level:
#    org.hibernate: SQL=DEBUG
#    org.type.descriptor: sql.BasicBinder=TRACE;